version: "3.8"

services:
  meilisearch:
    image: getmeili/meilisearch
    ports:
      - 7700:7700
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7700/health"]
      interval: 10s
      retries: 5